version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRESQL_PORT}:${POSTGRESQL_PORT}'
volumes:
  postgres:
